name: Snyk Container

on:
    push:
        branches: [main]   
    workflow_dispatch: 

env:
  IMAGE_NAME: "image:latest"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Snyk Check
        uses: snyk/actions/docker@master
        id: snyk
        continue-on-error: true
        with:
          image: ${{ env.IMAGE_NAME }}
          args: --org=${{ secrets.ORG_ID }} --severity-threshold=low 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Show Snyk Output
        run: |
          echo "Snyk Scan Status: ${{ steps.snyk.outcome }}"

  iac-security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2
          terraform_wrapper: false

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -upgrade -backend-config=dev.tfbackend

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false --var-file=dev.tfvars -out=output.tfplan && terraform show -no-color -json output.tfplan > plan_output.json

      - name: IaC Security
        id: snyk-iac
        uses: snyk/actions/iac@master
        continue-on-error: true
        with:
            file: terraform/plan_output.json
            args: >
                --org=${{ secrets.ORG_ID }} 
                --severity-threshold=high 
        env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check Snyk Status
        if: steps.snyk-iac.outcome == 'failure'
        run: |
            echo "Snyk detected High or Critical Issues. Breaking the build..."
            exit 1